### ISSUE TITLE
Ensure Overview points to index.html and remove /overview from URLs 

### ISSUE THREAD

**Issue by otisg** [sematext/docs#16]
What file does http://sematext.com/docs/ open?  I'm guessing index.html
What does http://sematext.com/docs/logs/ open?  Ooops, nothing. Why?  Because there is no index.html

This is just one example of this sort of problem.  There may be other such cases under /docs

We should:
* remove /overview from the URL.  Instead of opening http://sematext.com/docs/logs/overview/ when one clicks on Log Management > Overview, we should open http://sematext.com/docs/logs/
* keep "Overview" as the name in the navigation on the left side

CC @megastef

**Comment by megastef** [comment]
Done for logs, monitoring, sematext-docker-agent and logagent. See https://github.com/sematext/docs/commit/3090d54bf8ec276188c0facc4c7056d4c660bce6 https://github.com/sematext/docs/commit/ca499620666edaf2823bf6c4e6bc608824d6923c https://github.com/sematext/docs/commit/17b46ed0701ad103e4a01bd2027c44d9c26b2c02

**Comment by nmtien** [comment]
I fixed the PDF links for this changes.
