### ISSUE TITLE
Improve Integration pages

### ISSUE THREAD

**Issue by otisg** [sematext/docs#17]
Integrations are a top-level thing now.  I think that's good.  But:
- Integration should really be Integrations
- There are only a few things under Integrations
- The things that are under Integrations have outdated info/screenshots

We need to do something about this.
Here are the sorts of things we could do:
- in index.html add a big grid of integrations similar to http://sematext.com/spm/integrations/ , but not limited to SPM
- a page for each of the integrations.  We wouldn't want to duplicate what we have on http://sematext.com/spm/integrations/ so we would want to provide some different/additional info here.  For example, people often ask for A) a list of all metrics we monitor, and B) what each metric means.  We could provide A) relatively easily.  For B) we could enter what we know and encourage people to help us with missing metric descriptions through fork+PR.
- list here not just Monitoring integrations, but also Logs and Notification Hooks

**Comment by otisg** [comment]
I see Integrations under Performance Monitoring.
And I also see Integrations on top level.

**Comment by otisg** [comment]
I see Integrations under Performance Monitoring.
And I also see Integrations on top level.
Should we have only top level Integrations?

**Comment by nmtien** [comment]
I moved Monitoring/Integrations to top level Integrations
