### ISSUE TITLE
Kubernetes pod annotations inconsistent?

### ISSUE THREAD

**Issue by dabeck** [sematext/docs#178]
The docs state different annotation keys for the same functionality.

In [installation-docker.md](https://github.com/sematext/docs/blob/master/docs/logagent/installation-docker.md) it states: 

> The Kubernetes pod annotations `sematext.com/logs-token=<YOUR_LOGS_TOKEN>`, `sematext.com/logs-enabled=<true|false>`, and `sematext.com/logs-receiver-urls=<url,url,url>` are equivalent.

while the file [output-filter-kubernetes.md](https://github.com/sematext/docs/blob/master/docs/logagent/output-filter-kubernetes.md) says:

> Evaluates pod annotations for Sematext Cloud:
`sematext/logs-token=YOUR_LOGS_TOKEN` to set the log index
`sematext/logs-enabled=<true|false>` to switch logging per pod on or off
`sematext/logs-receiver-url=https://logsene-receiver.sematext.com/token` set Elasticsearch API endpoint for log ingestion
`sematext/logs-remove-fields=<field list>` to remove specific log fields from pod logs

**Comment by megastef** [comment]
Thank you for reporting. The right annotation keys are
- `sematextcom/logs-receiver-url` 
- `sematext.com/logs-token`
- `sematext.com/logs-enabled`
- `sematext.com/logs-remove-fields`

https://github.com/sematext/logagent-js/blob/master/lib/plugins/output-filter/kubernetes-enrichment.js#L96
