### ISSUE TITLE
Add Monitoring for Foo pages with metrics

### ISSUE THREAD

**Issue by otisg** [sematext/docs#23]
Under https://sematext.com/docs/integration/ we should have "Monitoring Foo" for every integration we have.  On it we should have, among other things, a table of metrics our agents collect.  There should be a column with metric names and a column with metric description.  Some descriptions we can find online and include in the table.  Others we will have to leave blank.

Here is a possibly outdated list of metrics we collect for various integrations:
https://sematext.atlassian.net/wiki/spaces/AF/pages/12189699/Metrics+grouped+by+application+type

**Comment by nmtien** [comment]
I will write a script to read all metric code, name, description (some reports have metric description such as haproxy) from our report config in spm/spm-reports/src/main/resources/cr-report-config/report

**Comment by megastef** [comment]
This page seems to be wrong: "Monitoring Api", with some Spark metrics inside: https://sematext.com/docs/integration/api/

**Comment by otisg** [comment]
Right.  And SolrCloud is missing, too.

**Comment by otisg** [comment]
I see SolrCloud now, but we still have "Monitoring Api"

**Comment by nmtien** [comment]
remove Api in commit 8d80f6d

**Comment by otisg** [comment]
Anything left to do here?

**Comment by nmtien** [comment]
Should we fill missing metrics description? i try to find metrics for akka but can't findit.

**Comment by otisg** [comment]
Tracked elsewhere
