### ISSUE TITLE
Move PHP-FPM to /docs/...

### ISSUE THREAD

**Issue by otisg** [sematext/docs#24]
We should move https://github.com/sematext/sematext-agent-httpd/blob/master/php-fpm.md and add it to Monitoring PHP - https://sematext.com/docs/integration/php/

We should just not forget to update the Apache and Nginx instructions: https://github.com/search?q=org%3Asematext+To+enable+PHP-FPM+stats+monitoring&type=Code

**Comment by megastef** [comment]
Just updated: https://sematext.com/docs/integration/php/

**Comment by otisg** [comment]
Tracked elsewhere.
