### ISSUE TITLE
Add a link to public integration instructions to each Integrations > Monitoring ... pages

### ISSUE THREAD

**Issue by otisg** [sematext/docs#25]
We provide instructions for each of our Monitoring integrations.  Each integration has a public view with those instructions, e.g. https://apps.sematext.com/ui/howto/Apache/overview .  We should make it easy for people looking at the docs to see how the integration is done.  I did this for Apache - https://github.com/sematext/docs/commit/4b043eccc5e59e6bc2c6bfddb8e5257f0bdcb64c - but we should do it for all other integrations, too.  Note that I was able to point to the Apache monitoring agent because it's open-source on Github, and we should do that for other agents that are open-source. Those agents that are not open-source simply won't have that Agent.... info.

**Comment by nmtien** [comment]
Some overviews don't work
https://apps.sematext.com/ui/howto/Hadoop/overview
https://apps.sematext.com/ui/howto/OS/overview
https://apps.sematext.com/ui/howto/PHP/overview
https://apps.sematext.com/ui/howto/Tracing/overview
https://apps.sematext.com/ui/howto/NginxPlus/overview

**Comment by otisg** [comment]
There is no "OS" integration.  PHP integration is a part of Apache and Nginx and NginxPlus.  Tracing is not an SPM integration.  Hadoop is https://apps.sematext.com/ui/howto/Hadoop-YARN/overview

**Comment by otisg** [comment]
@nmtien please look at the various Monitoring pages and the Instructions: .... stuff.  Those links are not clickable.
