### ISSUE TITLE
Move breadcrumb

### ISSUE THREAD

**Issue by otisg** [sematext/docs#26]
There is not much room in the header for the breadcrumb.

Could we please:
- move it down like shown below
- make each part of the breadcrumb clickable

![move-breadcrumb](https://user-images.githubusercontent.com/332580/31526974-4b740096-af98-11e7-8b81-9ecb94c253e6.png)

**Comment by otisg** [comment]
![screen shot 2017-10-16 at 6 48 07 pm](https://user-images.githubusercontent.com/332580/31638614-9d018f5c-b2a2-11e7-8c62-0707ec95acf1.png)

We should change this to look more like a breadcrumb and remove redundancy.  Maybe @goranbajic can help?

**Comment by otisg** [comment]
I still see redundancy.  I'm referring to "Monitoring Cassandra" appearing twice.  Maybe we can remove the big "Monitoring XXXX" because it's now a part of the breadcrumb.

Also, I think we can move the 3 icons on the right in the far right side of the breadcrumb and possibly adjust their colour so they are nicely visible.  That should pull the TOC up, which is nice because one won't have to scroll as much down to see the content.

**Comment by nmtien** [comment]
How about moving breadcrumb below title like this
![evlkse8ztn2h5bi8sd1gtw](https://user-images.githubusercontent.com/4736608/31919510-2b260138-b88d-11e7-9517-592bda2b6d94.png)

**Comment by otisg** [comment]
2 things:

1. there is still redundancy
2. Integrations (small) / Monitoring Apache (big, h1) would be better

**Comment by nmtien** [comment]
It should look like this?
![screenshot 2](https://user-images.githubusercontent.com/4736608/31920271-0d4bd7be-b892-11e7-84e3-84017c85e741.png)

**Comment by otisg** [comment]
Yeah, I think that's better!

**Comment by otisg** [comment]
Published.  Looks better.  Could we turn all parent elements of the breadcrumb into hyperlinks to let people navigate up.

**Comment by nmtien** [comment]
In fact all parents don't have link, each parent have an overview page can be serve as link, but it not alway true.
May be i will build link from url such as
https://sematext.com/docs/sematext-enterprise/faq/
parent will be https://sematext.com/docs/sematext-enterprise/

**Comment by otisg** [comment]
Note that some parts of the breadcrumbs are hyperlinked, but not all.  For example, look at https://sematext.com/docs/logs/syslog/ and you will see the "syslog" part is not hyperlinked.

**Comment by nmtien** [comment]
Because "syslog" is that page and "Overview" page are the same. So i don't link "syslog" to it self.

See this link
https://sematext.com/docs/logs/json-messages-over-syslog/
The link for parent "syslog" is 
https://sematext.com/docs/logs/syslog/ (this is "Overview" page).

**Comment by otisg** [comment]
Got it.  I think the font for the part of the breadcrumb that is small now should be a little big bigger and bold, and then I think we can close this issue.
