### ISSUE TITLE
Typo in docs, IGNORE_LOGS_PATTERNS should be IGNORE_LOGS_PATTERN

### ISSUE THREAD

**Issue by bkcsfi** [sematext/docs#67]
Hi,

The documentation at https://sematext.com/docs/logagent/installation-docker/ appears to come from this repo.  The environment var/parameter IGNORE_LOGS_PATTERNS mentioned in the docs does not seem to appear anywhere else (i.e in any other sematext repo).

I suspect this feature was not implemented.

Can you please clarify if the docs were perhaps prematurely updated or maybe there's a typo somewhere?

thanks

**Comment by megastef** [comment]
Hi, the feature applies to Logagent Docker plugin. 
See e.g.: https://github.com/sematext/logagent-js/blob/master/lib/plugins/input/docker/docker.js#L21

**Comment by bkcsfi** [comment]
thank you for the fast response.

I am running this docker image sematext/logagent:2.0.130

with environment variable `IGNORE_LOGS_PATTERNS=\/-\/`  but it's not filtering out those messages

perhaps logagent-js is not in logagent the docker image?

**Comment by otisg** [comment]
> perhaps logagent-js is not in logagent the docker image?

That would be weird -- that should be the main thing in there :)

**Comment by bkcsfi** [comment]
excellent..

the documentation says "IGNORE_LOGS_PATTERNS"

the code says "IGNORE_LOGS_PATTERN"
